language: python
python:
  - "3.8"

install:
  - mkdir /tmp/django
  - wget https://github.com/django/django/archive/3.0.tar.gz -O /tmp/django.tar.gz
  - tar -xzf -C /tmp/django django.tar.gz --strip-components=1
  - pip install /tmp/django
  - pip install .
  - cp tests/settings.py /tmp/django/tests/iseries_settings.py
  - cd /tmp/django/tests
  - pip install -r requirements/py3.txt

script:
  - cd /tmp/django-3.0/tests
  - ./runtests.py --setings=iseries_settings --noinput --keepdb
