language: python
python:
  - "3.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev

install:
  - mkdir /tmp/django
  - wget https://github.com/django/django/archive/3.0.tar.gz -O /tmp/django.tar.gz
  - tar -C /tmp/django -xzf /tmp/django.tar.gz --strip-components=1
  - pip install /tmp/django
  - pip install .
  - cp tests/settings.py /tmp/django/tests/iseries_settings.py
  - cd /tmp/django/tests
  - pip install -r requirements/py3.txt

script:
  - cd /tmp/django/tests
  - ./runtests.py --settings=iseries_settings --noinput --keepdb
