language: python
python:
  - "3.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev
    - unixodbc

before_install:
  - openssl aes-256-cbc -K $encrypted_0a7eaec557b5_key -iv $encrypted_0a7eaec557b5_iv -in iaccess_bin/ibm-iaccess-1.1.0.12-1.0.amd64.deb.enc -out /tmp/ibm-iaccess-1.1.0.12-1.0.amd64.deb -d

install:
  - sudo dpkg -i /tmp/ibm-iaccess-1.1.0.12-1.0.amd64.deb
  - mkdir /tmp/django
  - wget https://github.com/django/django/archive/3.0.tar.gz -O /tmp/django.tar.gz
  - tar -C /tmp/django -xzf /tmp/django.tar.gz --strip-components=1
  - pip install /tmp/django
  - pip install -r /tmp/django/requirements/py3.txt
  - pip install .

env:
  - DJANGO_SETTINGS_MODULE=tests.settings

script:
  - cd /tmp/django/tests
  - ./runtests.py aggregation query backends basic expressions generic_relations migrations ordering queries update select_for_update --noinput --keepdb
